### ISSUE TITLE
Add the the feature to insert straight to embedded database

### ISSUE THREAD

**Issue by MarcFerran** [abelsromero/embedded-mongodb-unit#2]
Please could you add the feature to add documents straight to "MongoDatabase"?
The "insertOne" and "insertMany" features would be georgeous.
Something similar to:
`public void insertOne(final String dataBase, final String collection, final String json) {
        final Document jsnObject = Document.parse(json);
        new MongoClient("localhost", PORT).getDatabase(dataBase).getCollection(collection).insertOne(jsnObject);
    }`

Thanks in advance.

**Comment by abelsromero** [comment]
Does the import feature cover your needs https://github.com/abelsromero/embedded-mongodb-unit#embeddedmongodbimport?
